# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

version: "3.9"  # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8181:80"
    environment:
      - NGINX_HOST=rasa.aetherproject.org
      - NGINX_PORT=80
  rasa:
    build:
      context: .
      dockerfile: rasa.Dockerfile
    container_name: docker-compose_rasa
    volumes:
      - .:/etc/rasa/endpoints
    command:
      - run
      - --endpoints
      - /etc/rasa/endpoints/endpoints.yml
      - --enable-api
      - --credentials
      - /etc/rasa/endpoints/credentials.yml
  rasa-ms:
    build:
      context: ..
      dockerfile: build/rasa-model-server/Dockerfile
    container_name: docker-compose_rasa-ms
    command:
      - /usr/local/bin/rasa-model-server
