// Code generated by oapi-codegen. DO NOT EDIT.
// Code generated by oapi-codegen. DO NOT EDIT.
// Code generated by oapi-codegen. DO NOT EDIT.
// Code generated by oapi-codegen. DO NOT EDIT.
// SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

package aether

import (
	"github.com/labstack/echo/v4"
	"net/http"
)

// ServerImpl -
type ServerImpl struct {
	config *Enterprises
}

func NewServer(config *Enterprises) ServerInterface {
	return &ServerImpl{
		config: config,
	}
}

// DeleteConnectivityServices DELETE /connectivity-services
// (DELETE /aether/v2.0.0/{target}/connectivity-services)
func (w *ServerImpl) DeleteConnectivityServices(ctx echo.Context, target Target) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GetConnectivityServices GET /connectivity-services
// (GET /aether/v2.0.0/{target}/connectivity-services)
func (w *ServerImpl) GetConnectivityServices(ctx echo.Context, target Target) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// PostConnectivityServices POST /connectivity-services
// (POST /aether/v2.0.0/{target}/connectivity-services)
func (w *ServerImpl) PostConnectivityServices(ctx echo.Context, target Target) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DeleteConnectivityServicesConnectivityService DELETE /connectivity-services/connectivity-service
// (DELETE /aether/v2.0.0/{target}/connectivity-services/connectivity-service/{connectivity-service-id})
func (w *ServerImpl) DeleteConnectivityServicesConnectivityService(ctx echo.Context, target Target, connectivityServiceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /connectivity-services/connectivity-service
// (GET /aether/v2.0.0/{target}/connectivity-services/connectivity-service/{connectivity-service-id})
func (w *ServerImpl) GetConnectivityServicesConnectivityService(ctx echo.Context, target Target, connectivityServiceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /connectivity-services/connectivity-service
// (POST /aether/v2.0.0/{target}/connectivity-services/connectivity-service/{connectivity-service-id})
func (w *ServerImpl) PostConnectivityServicesConnectivityService(ctx echo.Context, target Target, connectivityServiceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises
// (DELETE /aether/v2.0.0/{target}/enterprises)
func (w *ServerImpl) DeleteEnterprises(ctx echo.Context, target Target) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises
// (GET /aether/v2.0.0/{target}/enterprises)
func (w *ServerImpl) GetEnterprises(ctx echo.Context, target Target) error {
	return ctx.JSON(http.StatusOK, w.config)
}

// POST /enterprises
// (POST /aether/v2.0.0/{target}/enterprises)
func (w *ServerImpl) PostEnterprises(ctx echo.Context, target Target) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id})
func (w *ServerImpl) DeleteEnterprisesEnterprise(ctx echo.Context, target Target, enterpriseId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id})
func (w *ServerImpl) GetEnterprisesEnterprise(ctx echo.Context, target Target, enterpriseId string) error {
	for _, e := range *w.config.Enterprise {
		if e.EnterpriseId == enterpriseId {
			return ctx.JSON(http.StatusOK, e)
		}
	}

	return echo.NewHTTPError(http.StatusNotFound)
}

// POST /enterprises/enterprise
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id})
func (w *ServerImpl) PostEnterprisesEnterprise(ctx echo.Context, target Target, enterpriseId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/application
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseApplication(ctx echo.Context, target Target, enterpriseId string, applicationId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/application
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id})
func (w *ServerImpl) GetEnterprisesEnterpriseApplication(ctx echo.Context, target Target, enterpriseId string, applicationId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/application
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id})
func (w *ServerImpl) PostEnterprisesEnterpriseApplication(ctx echo.Context, target Target, enterpriseId string, applicationId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseApplicationEndpoint(ctx echo.Context, target Target, enterpriseId string, applicationId string, endpointId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id})
func (w *ServerImpl) GetEnterprisesEnterpriseApplicationEndpoint(ctx echo.Context, target Target, enterpriseId string, applicationId string, endpointId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id})
func (w *ServerImpl) PostEnterprisesEnterpriseApplicationEndpoint(ctx echo.Context, target Target, enterpriseId string, applicationId string, endpointId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/mbr
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/mbr)
func (w *ServerImpl) DeleteEnterprisesEnterpriseApplicationEndpointMbr(ctx echo.Context, target Target, enterpriseId string, applicationId string, endpointId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/mbr
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/mbr)
func (w *ServerImpl) GetEnterprisesEnterpriseApplicationEndpointMbr(ctx echo.Context, target Target, enterpriseId string, applicationId string, endpointId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/mbr
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/mbr)
func (w *ServerImpl) PostEnterprisesEnterpriseApplicationEndpointMbr(ctx echo.Context, target Target, enterpriseId string, applicationId string, endpointId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/connectivity-service
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/connectivity-service/{connectivity-service})
func (w *ServerImpl) DeleteEnterprisesEnterpriseConnectivityService(ctx echo.Context, target Target, enterpriseId string, connectivityService string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/connectivity-service
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/connectivity-service/{connectivity-service})
func (w *ServerImpl) GetEnterprisesEnterpriseConnectivityService(ctx echo.Context, target Target, enterpriseId string, connectivityService string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/connectivity-service
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/connectivity-service/{connectivity-service})
func (w *ServerImpl) PostEnterprisesEnterpriseConnectivityService(ctx echo.Context, target Target, enterpriseId string, connectivityService string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSite(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSite(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSite(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteDeviceGroup(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteDeviceGroup(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteDeviceGroup(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/device
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/device/{device-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteDeviceGroupDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string, deviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/device
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/device/{device-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteDeviceGroupDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string, deviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/device
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/device/{device-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteDeviceGroupDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string, deviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/mbr
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/mbr)
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteDeviceGroupMbr(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/mbr
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/mbr)
func (w *ServerImpl) GetEnterprisesEnterpriseSiteDeviceGroupMbr(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/mbr
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device-group/{device-group-id}/mbr)
func (w *ServerImpl) PostEnterprisesEnterpriseSiteDeviceGroupMbr(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceGroupId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/device
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device/{device-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/device
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device/{device-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/device
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/device/{device-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, deviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/imsi-definition
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/imsi-definition)
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteImsiDefinition(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/imsi-definition
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/imsi-definition)
func (w *ServerImpl) GetEnterprisesEnterpriseSiteImsiDefinition(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/imsi-definition
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/imsi-definition)
func (w *ServerImpl) PostEnterprisesEnterpriseSiteImsiDefinition(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/ip-domain
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/ip-domain/{ip-domain-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteIpDomain(ctx echo.Context, target Target, enterpriseId string, siteId string, ipDomainId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/ip-domain
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/ip-domain/{ip-domain-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteIpDomain(ctx echo.Context, target Target, enterpriseId string, siteId string, ipDomainId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/ip-domain
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/ip-domain/{ip-domain-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteIpDomain(ctx echo.Context, target Target, enterpriseId string, siteId string, ipDomainId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring)
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteMonitoring(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring)
func (w *ServerImpl) GetEnterprisesEnterpriseSiteMonitoring(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring)
func (w *ServerImpl) PostEnterprisesEnterpriseSiteMonitoring(ctx echo.Context, target Target, enterpriseId string, siteId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring/edge-device
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring/edge-device/{edge-device-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteMonitoringEdgeDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, edgeDeviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring/edge-device
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring/edge-device/{edge-device-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteMonitoringEdgeDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, edgeDeviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring/edge-device
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/monitoring/edge-device/{edge-device-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteMonitoringEdgeDevice(ctx echo.Context, target Target, enterpriseId string, siteId string, edgeDeviceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/sim-card
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/sim-card/{sim-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSimCard(ctx echo.Context, target Target, enterpriseId string, siteId string, simId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/sim-card
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/sim-card/{sim-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSimCard(ctx echo.Context, target Target, enterpriseId string, siteId string, simId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/sim-card
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/sim-card/{sim-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSimCard(ctx echo.Context, target Target, enterpriseId string, siteId string, simId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSlice(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSlice(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSlice(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/device-group
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/device-group/{device-group})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSliceDeviceGroup(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, deviceGroup string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/device-group
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/device-group/{device-group})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSliceDeviceGroup(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, deviceGroup string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/device-group
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/device-group/{device-group})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSliceDeviceGroup(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, deviceGroup string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/filter
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/filter/{application})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSliceFilter(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, application string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/filter
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/filter/{application})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSliceFilter(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, application string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/filter
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/filter/{application})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSliceFilter(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, application string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/mbr
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/mbr)
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSliceMbr(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/mbr
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/mbr)
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSliceMbr(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/mbr
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/mbr)
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSliceMbr(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/priority-traffic-rule
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/priority-traffic-rule/{priority-traffic-rule-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSlicePriorityTrafficRule(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, priorityTrafficRuleId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/priority-traffic-rule
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/priority-traffic-rule/{priority-traffic-rule-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSlicePriorityTrafficRule(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, priorityTrafficRuleId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/priority-traffic-rule
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/slice/{slice-id}/priority-traffic-rule/{priority-traffic-rule-id})
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell/{small-cell-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSlicePriorityTrafficRule(ctx echo.Context, target Target, enterpriseId string, siteId string, sliceId string, priorityTrafficRuleId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell/{small-cell-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteSmallCell(ctx echo.Context, target Target, enterpriseId string, siteId string, smallCellId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell/{small-cell-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteSmallCell(ctx echo.Context, target Target, enterpriseId string, siteId string, smallCellId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/small-cell/{small-cell-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteSmallCell(ctx echo.Context, target Target, enterpriseId string, siteId string, smallCellId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/site/{site-id}/upf
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/upf/{upf-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseSiteUpf(ctx echo.Context, target Target, enterpriseId string, siteId string, upfId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/site/{site-id}/upf
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/upf/{upf-id})
func (w *ServerImpl) GetEnterprisesEnterpriseSiteUpf(ctx echo.Context, target Target, enterpriseId string, siteId string, upfId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/site/{site-id}/upf
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/site/{site-id}/upf/{upf-id})
func (w *ServerImpl) PostEnterprisesEnterpriseSiteUpf(ctx echo.Context, target Target, enterpriseId string, siteId string, upfId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/template
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/template/{template-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseTemplate(ctx echo.Context, target Target, enterpriseId string, templateId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/template
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/template/{template-id})
func (w *ServerImpl) GetEnterprisesEnterpriseTemplate(ctx echo.Context, target Target, enterpriseId string, templateId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/template
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/template/{template-id})
func (w *ServerImpl) PostEnterprisesEnterpriseTemplate(ctx echo.Context, target Target, enterpriseId string, templateId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/template/{template-id}/mbr
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/template/{template-id}/mbr)
func (w *ServerImpl) DeleteEnterprisesEnterpriseTemplateMbr(ctx echo.Context, target Target, enterpriseId string, templateId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/template/{template-id}/mbr
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/template/{template-id}/mbr)
func (w *ServerImpl) GetEnterprisesEnterpriseTemplateMbr(ctx echo.Context, target Target, enterpriseId string, templateId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/template/{template-id}/mbr
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/template/{template-id}/mbr)
func (w *ServerImpl) PostEnterprisesEnterpriseTemplateMbr(ctx echo.Context, target Target, enterpriseId string, templateId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// DELETE /enterprises/enterprise/{enterprise-id}/traffic-class
// (DELETE /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/traffic-class/{traffic-class-id})
func (w *ServerImpl) DeleteEnterprisesEnterpriseTrafficClass(ctx echo.Context, target Target, enterpriseId string, trafficClassId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// GET /enterprises/enterprise/{enterprise-id}/traffic-class
// (GET /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/traffic-class/{traffic-class-id})
func (w *ServerImpl) GetEnterprisesEnterpriseTrafficClass(ctx echo.Context, target Target, enterpriseId string, trafficClassId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}

// POST /enterprises/enterprise/{enterprise-id}/traffic-class
// (POST /aether/v2.0.0/{target}/enterprises/enterprise/{enterprise-id}/traffic-class/{traffic-class-id})
func (w *ServerImpl) PostEnterprisesEnterpriseTrafficClass(ctx echo.Context, target Target, enterpriseId string, trafficClassId string) error {
	return echo.NewHTTPError(http.StatusNotImplemented)
}
